version: '3.8'

services:
  app:
    build: .
    container_name: imza-backend
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./.env:/app/.env
      - data_volume:/app/data
    restart: always
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1

volumes:
  data_volume:
