version: '3.8'

services:
  app:
    build: .
    container_name: imza-backend
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./imza_database.db:/app/imza_database.db
      - ./.env:/app/.env
    restart: always
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
